# Generated by Django 5.1.5 on 2025-02-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_surah'),
    ]

    operations = [
        migrations.AddField(
            model_name='surah',
            name='arabic_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surah',
            name='pronunciation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surah',
            name='turkish_translation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
