# Generated by Django 5.1.5 on 2025-02-08 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_surah_arabic_text_surah_pronunciation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorizedSurah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memorized_at', models.DateTimeField(auto_now_add=True)),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.surah')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'surah')},
            },
        ),
    ]
