# Generated by Django 5.2.6 on 2025-09-11 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surahs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorizedAyet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_memorized', models.DateField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('ayet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surahs.ayet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorized_ayets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'ayet')},
            },
        ),
    ]
