# Generated by Django 5.2.6 on 2025-09-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_audioanalysisresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioanalysisresult',
            name='differences',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
