# Generated by Django 5.2.6 on 2025-10-05 04:45

import audio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_audioanalysisresult_differences'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiosubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('checking', 'İnceleniyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='audioanalysisresult',
            name='differences',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='audioanalysisresult',
            name='similarity',
            field=models.FloatField(help_text='0–100 arası benzerlik yüzdesi'),
        ),
        migrations.AlterField(
            model_name='audiosubmission',
            name='audio_file',
            field=models.FileField(upload_to=audio.models.user_audio_path),
        ),
    ]
