# Generated by Django 5.2.6 on 2025-09-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TajweedRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('example_ar', models.TextField(help_text='Ayet örneği - Arapça')),
                ('example_tr', models.TextField(blank=True, help_text='Ayet anlamı - Türkçe')),
                ('audio_url', models.URLField(blank=True, help_text='Opsiyonel: Sesli örnek')),
            ],
        ),
    ]
