# Generated by Django 5.2.6 on 2025-09-10 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('total_ayahs', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ayet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('text_ar', models.TextField()),
                ('text_tr', models.TextField(blank=True)),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayets', to='surahs.surah')),
            ],
        ),
    ]
